# Generated by Django 2.1.4 on 2018-12-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribuidor',
            options={'verbose_name': 'Distribuidor', 'verbose_name_plural': 'Distribuidores'},
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='peso',
            field=models.CharField(max_length=200, verbose_name='Peso'),
        ),
    ]
